REPLACE INTO `xcart_languages` (`code`, `name`, `value`, `topic`) VALUES('en','module_descr_XPayments_Subscriptions','This module allows to create product subscriptions and process them via X-Payments module.','Modules');
REPLACE INTO `xcart_languages` (`code`, `name`, `value`, `topic`) VALUES('en','opt_xps_rebill_attempts','Number of rebill attempts for an unsuccessful charge','Options');
REPLACE INTO `xcart_languages` (`code`, `name`, `value`, `topic`) VALUES('en','opt_xps_rebill_attempt_period','How often to attempt rebills for an unsuccessful charge (in days)','Options');
REPLACE INTO `xcart_languages` (`code`, `name`, `value`, `topic`) VALUES('en','opt_xps_notification_days','Notify the customer of the upcoming payment X days in advance','Options');


REPLACE INTO `xcart_languages` (`code`, `name`, `value`, `topic`) VALUES('en', 'eml_xps_upcoming_rebill_info', 'The next payment will be made in {{days}} days', 'E-Mail');
REPLACE INTO `xcart_languages` (`code`, `name`, `value`, `topic`) VALUES('en', 'eml_xps_upcoming_rebill_subj', 'Pending payment information', 'E-Mail');
REPLACE INTO `xcart_languages` (`code`, `name`, `value`, `topic`) VALUES('en', 'eml_xps_subscription_finished_info', 'The subscriptions was finished (all expected payments was processed)', 'Labels');
REPLACE INTO `xcart_languages` (`code`, `name`, `value`, `topic`) VALUES('en', 'eml_xps_subscription_finished_subj', 'The subscriptions was finished', 'Labels');

REPLACE INTO `xcart_languages` (`code`, `name`, `value`, `topic`) VALUES('en', 'eml_xps_subscription_stopped_by_admin_info', 'The subscription was suspended by site administrator', 'E-Mail');
REPLACE INTO `xcart_languages` (`code`, `name`, `value`, `topic`) VALUES('en', 'eml_xps_subscription_stopped_info', 'The subscription was suspended after {{attempts}} unsuccessful payment attempts', 'E-Mail');
REPLACE INTO `xcart_languages` (`code`, `name`, `value`, `topic`) VALUES('en', 'eml_xps_subscription_stopped_subj', 'The subscription was suspended', 'E-Mail');
REPLACE INTO `xcart_languages` (`code`, `name`, `value`, `topic`) VALUES('en', 'eml_xps_subscription_restarted_info', 'The subscription was restarted by site administrator', 'E-Mail');
REPLACE INTO `xcart_languages` (`code`, `name`, `value`, `topic`) VALUES('en', 'eml_xps_subscription_restarted_subj', 'The subscription was restarted', 'E-Mail');

REPLACE INTO `xcart_languages` (`code`, `name`, `value`, `topic`) VALUES('en', 'module_name_XPayments_Subscriptions', 'X-Payments Subscriptions', 'Modules');
REPLACE INTO `xcart_languages` (`code`, `name`, `value`, `topic`) VALUES('en', 'option_title_XPayments_Subscriptions', 'X-Payments Subscriptions', 'Options');

REPLACE INTO `xcart_languages` (`code`, `name`, `value`, `topic`) VALUES('en', 'lbl_xps_active', 'Active', 'Labels');
REPLACE INTO `xcart_languages` (`code`, `name`, `value`, `topic`) VALUES('en', 'lbl_xps_all_orders', 'Show all orders', 'Labels');
REPLACE INTO `xcart_languages` (`code`, `name`, `value`, `topic`) VALUES('en', 'lbl_xps_annualy', 'Annualy', 'Labels');
REPLACE INTO `xcart_languages` (`code`, `name`, `value`, `topic`) VALUES('en', 'lbl_xps_billing_period', 'Billing period', 'Labels');
REPLACE INTO `xcart_languages` (`code`, `name`, `value`, `topic`) VALUES('en', 'lbl_xps_billing_priod_info', 'Bill every {{period}} days', 'Labels');
REPLACE INTO `xcart_languages` (`code`, `name`, `value`, `topic`) VALUES('en', 'lbl_xps_daily', 'Daily', 'Labels');
REPLACE INTO `xcart_languages` (`code`, `name`, `value`, `topic`) VALUES('en', 'lbl_xps_date_of_next_payment', 'The date of the next payment', 'Labels');
REPLACE INTO `xcart_languages` (`code`, `name`, `value`, `topic`) VALUES('en', 'lbl_xps_days', 'Day(s)', 'Labels');
REPLACE INTO `xcart_languages` (`code`, `name`, `value`, `topic`) VALUES('en', 'lbl_xps_each', 'Each', 'Labels');
REPLACE INTO `xcart_languages` (`code`, `name`, `value`, `topic`) VALUES('en', 'lbl_xps_each_M', 'Each {{number}}-th day of every month', 'Labels');
REPLACE INTO `xcart_languages` (`code`, `name`, `value`, `topic`) VALUES('en', 'lbl_xps_each_M_R', '{{number}} day(s) till the end of each month', 'Labels');
REPLACE INTO `xcart_languages` (`code`, `name`, `value`, `topic`) VALUES('en', 'lbl_xps_each_W', 'Each {{number}}', 'Labels');
REPLACE INTO `xcart_languages` (`code`, `name`, `value`, `topic`) VALUES('en', 'lbl_xps_each_Y', 'Each {{number}}-th day of every year', 'Labels');
REPLACE INTO `xcart_languages` (`code`, `name`, `value`, `topic`) VALUES('en', 'lbl_xps_each_Y_R', '{{number}} day(s) till the end of each year', 'Labels');
REPLACE INTO `xcart_languages` (`code`, `name`, `value`, `topic`) VALUES('en', 'lbl_xps_every', 'Every', 'Labels');
REPLACE INTO `xcart_languages` (`code`, `name`, `value`, `topic`) VALUES('en', 'lbl_xps_every__days', 'Every {{number}} day(s)', 'Labels');
REPLACE INTO `xcart_languages` (`code`, `name`, `value`, `topic`) VALUES('en', 'lbl_xps_every__months', 'Every {{number}} month(s)', 'Labels');
REPLACE INTO `xcart_languages` (`code`, `name`, `value`, `topic`) VALUES('en', 'lbl_xps_every__weeks', 'Every {{number}} week(s)', 'Labels');
REPLACE INTO `xcart_languages` (`code`, `name`, `value`, `topic`) VALUES('en', 'lbl_xps_every__years', 'Every {{number}} year(s)', 'Labels');
REPLACE INTO `xcart_languages` (`code`, `name`, `value`, `topic`) VALUES('en', 'lbl_xps_find_orders', 'Find all orders for this subscription', 'Labels');
REPLACE INTO `xcart_languages` (`code`, `name`, `value`, `topic`) VALUES('en', 'lbl_xps_finished', 'Finished', 'Labels');
REPLACE INTO `xcart_languages` (`code`, `name`, `value`, `topic`) VALUES('en', 'lbl_xps_force_save_cards', 'Your credit card will be saved in our secure vault for subscription products you are buying now.', 'Labels');
REPLACE INTO `xcart_languages` (`code`, `name`, `value`, `topic`) VALUES('en', 'lbl_xps_friday', 'Friday', 'Labels');
REPLACE INTO `xcart_languages` (`code`, `name`, `value`, `topic`) VALUES('en', 'lbl_xps_monday', 'Monday', 'Labels');
REPLACE INTO `xcart_languages` (`code`, `name`, `value`, `topic`) VALUES('en', 'lbl_xps_month', 'Month', 'Labels');
REPLACE INTO `xcart_languages` (`code`, `name`, `value`, `topic`) VALUES('en', 'lbl_xps_monthly', 'Monthly', 'Labels');
REPLACE INTO `xcart_languages` (`code`, `name`, `value`, `topic`) VALUES('en', 'lbl_xps_months', 'Month(s)', 'Labels');
REPLACE INTO `xcart_languages` (`code`, `name`, `value`, `topic`) VALUES('en', 'lbl_xps_next_bill_date', 'Next bill date', 'Labels');
REPLACE INTO `xcart_languages` (`code`, `name`, `value`, `topic`) VALUES('en', 'lbl_xps_no_subscriptions', 'No subscriptions', 'Labels');
REPLACE INTO `xcart_languages` (`code`, `name`, `value`, `topic`) VALUES('en', 'lbl_xps_none_subscription_orders', 'Show non-subscription orders only', 'Labels');
REPLACE INTO `xcart_languages` (`code`, `name`, `value`, `topic`) VALUES('en', 'lbl_xps_not_created', 'Not created', 'Labels');
REPLACE INTO `xcart_languages` (`code`, `name`, `value`, `topic`) VALUES('en', 'lbl_xps_number_suffix', '-th day of', 'Labels');
REPLACE INTO `xcart_languages` (`code`, `name`, `value`, `topic`) VALUES('en', 'lbl_xps_payments_left', 'Payments left', 'Labels');
REPLACE INTO `xcart_languages` (`code`, `name`, `value`, `topic`) VALUES('en', 'lbl_xps_planned_bill_date', 'Planned bill date', 'Labels');
REPLACE INTO `xcart_languages` (`code`, `name`, `value`, `topic`) VALUES('en', 'lbl_xps_rebill_periods', 'Re-bill periods', 'Labels');
REPLACE INTO `xcart_languages` (`code`, `name`, `value`, `topic`) VALUES('en', 'lbl_xps_relaunch', 'Re-launch', 'Labels');
REPLACE INTO `xcart_languages` (`code`, `name`, `value`, `topic`) VALUES('en', 'lbl_xps_reverse', 'Count days from the end', 'Labels');
REPLACE INTO `xcart_languages` (`code`, `name`, `value`, `topic`) VALUES('en', 'lbl_xps_reverse_note', '<strong>Note:</strong> if the month is shorter than <span class="number"></span> days, subcription will not be charged this month. Switch the "Count days from the end" option and set corresponding day number to charge subscription every month.', 'Labels');
REPLACE INTO `xcart_languages` (`code`, `name`, `value`, `topic`) VALUES('en', 'lbl_xps_saturday', 'Saturday', 'Labels');
REPLACE INTO `xcart_languages` (`code`, `name`, `value`, `topic`) VALUES('en', 'lbl_xps_setup_fee', 'Setup fee', 'Labels');
REPLACE INTO `xcart_languages` (`code`, `name`, `value`, `topic`) VALUES('en', 'lbl_xps_show_calendar', 'Show calendar', 'Labels');
REPLACE INTO `xcart_languages` (`code`, `name`, `value`, `topic`) VALUES('en', 'lbl_xps_stop', 'Stop', 'Labels');
REPLACE INTO `xcart_languages` (`code`, `name`, `value`, `topic`) VALUES('en', 'lbl_xps_stopped', 'Stopped', 'Labels');
REPLACE INTO `xcart_languages` (`code`, `name`, `value`, `topic`) VALUES('en', 'lbl_xps_subscriptions', 'Subscriptions', 'Labels');
REPLACE INTO `xcart_languages` (`code`, `name`, `value`, `topic`) VALUES('en', 'lbl_xps_subscription_fee', 'Subscription fee', 'Labels');
REPLACE INTO `xcart_languages` (`code`, `name`, `value`, `topic`) VALUES('en', 'lbl_xps_subscription_info', 'Subscription Info', 'Labels');
REPLACE INTO `xcart_languages` (`code`, `name`, `value`, `topic`) VALUES('en', 'lbl_xps_subscription_orders', 'Show subscriptions only', 'Labels');
REPLACE INTO `xcart_languages` (`code`, `name`, `value`, `topic`) VALUES('en', 'lbl_xps_subscription_product', 'This is a subscription product', 'Labels');
REPLACE INTO `xcart_languages` (`code`, `name`, `value`, `topic`) VALUES('en', 'lbl_xps_subscription_status', 'Subscription status', 'Labels');
REPLACE INTO `xcart_languages` (`code`, `name`, `value`, `topic`) VALUES('en', 'lbl_xps_sunday', 'Sunday', 'Labels');
REPLACE INTO `xcart_languages` (`code`, `name`, `value`, `topic`) VALUES('en', 'lbl_xps_thursday', 'Thursday', 'Labels');
REPLACE INTO `xcart_languages` (`code`, `name`, `value`, `topic`) VALUES('en', 'lbl_xps_total_payments', 'Total payments', 'Labels');
REPLACE INTO `xcart_languages` (`code`, `name`, `value`, `topic`) VALUES('en', 'lbl_xps_tuesday', 'Tuesday', 'Labels');
REPLACE INTO `xcart_languages` (`code`, `name`, `value`, `topic`) VALUES('en', 'lbl_xps_wednesday', 'Wednesday', 'Labels');
REPLACE INTO `xcart_languages` (`code`, `name`, `value`, `topic`) VALUES('en', 'lbl_xps_week', 'Week', 'Labels');
REPLACE INTO `xcart_languages` (`code`, `name`, `value`, `topic`) VALUES('en', 'lbl_xps_weekly', 'Weekly', 'Labels');
REPLACE INTO `xcart_languages` (`code`, `name`, `value`, `topic`) VALUES('en', 'lbl_xps_weeks', 'Week(s)', 'Labels');
REPLACE INTO `xcart_languages` (`code`, `name`, `value`, `topic`) VALUES('en', 'lbl_xps_year', 'Year', 'Labels');
REPLACE INTO `xcart_languages` (`code`, `name`, `value`, `topic`) VALUES('en', 'lbl_xps_years', 'Year(s)', 'Labels');

REPLACE INTO `xcart_languages` (`code`, `name`, `value`, `topic`) VALUES('en', 'lbl_xps_click_to_view_related_order', 'Click to view related order', 'Labels');
REPLACE INTO `xcart_languages` (`code`, `name`, `value`, `topic`) VALUES('en', 'lbl_xps_failed_attempt', 'Failed attempt', 'Labels');
REPLACE INTO `xcart_languages` (`code`, `name`, `value`, `topic`) VALUES('en', 'lbl_xps_scheduled_payment', 'Scheduled payment', 'Labels');
REPLACE INTO `xcart_languages` (`code`, `name`, `value`, `topic`) VALUES('en', 'lbl_xps_succcessfully_billed', 'Successfully billed', 'Labels');
